source :rubygems

gem 'rails', '~>2.3'
gem 'rspec', '~>1.3'
gem 'rspec-rails', '~>1.3'
gem 'sqlite3'
gem 'ruby-debug', :platforms => :ruby_18
gem 'test-unit', '~>1.2', :platforms => :ruby_19

gem 'dusen', :path => '../..'
