source 'https://rubygems.org'

gem 'rails', '~>4.0'
gem 'rspec'
gem 'rspec-rails'
gem 'mysql2'
gem 'rspec_candy'
gem 'ruby-debug', :platforms => :ruby_18
gem 'database_cleaner'
gem 'andand'
gem 'pry-rails'

gem 'dusen', :path => '../..'
